-- Phase 4 Exercises SQL INSERT Statements
-- Flexibility, Balance, Medicine Ball, Stability Ball & Cardio Variations (33 exercises)
-- Generated on: 2025-12-20

-- First, enhance the schema for Phase 4 exercises
BEGIN;

-- Add new columns for Phase 4 features
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS balance_requirement VARCHAR(20) DEFAULT 'none';
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS flexibility_type VARCHAR(20) DEFAULT 'static';
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS power_metrics jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS progression_level INTEGER DEFAULT 3;
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS equipment_modifiers jsonb DEFAULT '{}'::jsonb;

-- Add check constraints for enum validation
ALTER TABLE public.exercises ADD CONSTRAINT chk_balance_requirement 
    CHECK (balance_requirement IN ('none', 'static', 'dynamic', 'advanced'));

ALTER TABLE public.exercises ADD CONSTRAINT chk_flexibility_type 
    CHECK (flexibility_type IN ('static', 'dynamic', 'proprioceptive'));

-- Create index for better performance on new columns
CREATE INDEX IF NOT EXISTS idx_exercises_balance_requirement ON public.exercises(balance_requirement);
CREATE INDEX IF NOT EXISTS idx_exercises_flexibility_type ON public.exercises(flexibility_type);
CREATE INDEX IF NOT EXISTS idx_exercises_progression_level ON public.exercises(progression_level);

COMMIT;

-- ================================================================
-- FLEXIBILITY EXERCISES (8)
-- ================================================================

-- Pigeon Pose (Hip flexibility)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'pigeon_pose_hip_flexibility_001',
  'Pigeon Pose',
  'flexibility',
  'Hips',
  ARRAY['Glutes', 'Lower Back']::text[],
  ARRAY['mat']::text[],
  'Pigeon Pose is a powerful hip opener that stretches the hip flexors, glutes, and piriformis muscle while improving hip mobility.',
  '[Start in downward dog position.', 'Bring your right knee forward toward your right wrist.', 'Slide your right foot toward your left wrist.', 'Lower your right hip toward the ground.', 'Extend your left leg straight back behind you.', 'Keep your hips squared to the front.', 'Hold for 30-60 seconds, breathing deeply.]'::jsonb,
  ARRAY['Deep hip stretch', 'Improves hip mobility', 'Opens chest and shoulders', 'Reduces lower back tension']::text[],
  'https://www.youtube.com/watch?v=7-1y2Uehs_E',
  'https://images.unsplash.com/photo-1588421357574-87938a86fa28?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  60,
  15,
  'none',
  'static',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  2,
  '{"recommended_duration": "30-60 seconds", "target_area": "hip_flexors"}'::jsonb,
  '{"secondary_muscles":["glutes","lower_back"],"phase":4,"exercise_category":"flexibility"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Butterfly Stretch (Hip opener)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'butterfly_stretch_hip_opener_002',
  'Butterfly Stretch',
  'flexibility',
  'Groin',
  ARRAY['Hips', 'Inner Thighs']::text[],
  ARRAY['mat']::text[],
  'Butterfly stretch opens the hips and groin, improving flexibility for athletes and daily movement while relieving tension.',
  ['Sit on the floor with your back straight.',
   'Bring the soles of your feet together and hold onto your ankles.',
   'Gently pull your feet toward your body.',
   'Allow your knees to fall toward the ground.',
   'Lean forward slightly to deepen the stretch.',
   'Hold for 20-45 seconds.',
   'Keep your spine tall and breathe deeply.']::jsonb,
  ARRAY['Opens hips and groin', 'Improves flexibility', 'Alleviates hip tightness', 'Prepares for deeper stretches']::text[],
  'https://www.youtube.com/watch?v=6eL7w1ZZe38',
  'https://images.unsplash.com/photo-1588421357574-87938a86fa28?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  55,
  12,
  'none',
  'static',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  1,
  '{"recommended_duration": "20-45 seconds", "target_area": "groin_hips"}'::jsonb,
  '{"secondary_muscles":["hips","inner_thighs"],"phase":4,"exercise_category":"flexibility"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Seated Forward Fold (Hamstring/Spinal flexibility)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'seated_forward_fold_hamspine_003',
  'Seated Forward Fold',
  'flexibility',
  'Hamstrings',
  ARRAY['Lower Back', 'Calves']::text[],
  ARRAY['mat']::text[],
  'Seated Forward Fold provides a deep stretch for hamstrings and spine while calming the mind and improving posture.',
  ['Sit on the floor with legs extended straight in front of you.',
   'Keep your back straight and lengthen your spine.',
   'Inhale as you reach your arms up overhead.',
   'Exhale and hinge at your hips, folding forward.',
   'Keep your knees slightly bent to protect hamstrings.',
   'Hold your shins or feet (if accessible).',
   'Hold for 30-60 seconds, breathing deeply.']::jsonb,
  ARRAY['Deep hamstring stretch', 'Spinal flexibility', 'Calms nervous system', 'Improves posture']::text[],
  'https://www.youtube.com/watch?v=2h7pV4_xwXU',
  'https://images.unsplash.com/photo-1588421357574-87938a86fa28?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  58,
  14,
  'static',
  'static',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  2,
  '{"recommended_duration": "30-60 seconds", "target_area": "hamstrings"}'::jsonb,
  '{"secondary_muscles":["lower_back","calves"],"phase":4,"exercise_category":"flexibility"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Thread the Needle (Spinal mobility)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'thread_the_needle_spinal_004',
  'Thread the Needle',
  'flexibility',
  'Upper Back',
  ARRAY['Shoulders', 'Chest']::text[],
  ARRAY['mat']::text[],
  'Thread the Needle gently twists the spine, improving spinal mobility while opening the shoulders and chest.',
  ['Start on all fours in table position.',
   'Inhale and reach your right arm straight up toward the ceiling.',
   'Exhale and thread your right arm under your left arm.',
   'Lower your right shoulder and cheek to the ground.',
   'Extend your left arm forward or rest on your head.',
   'Hold for 30 seconds, breathing into the stretch.',
   'Repeat on the other side.']::jsonb,
  ARRAY['Spinal mobility', 'Shoulder opening', 'Chest stretch', 'Gentle twist']::text[],
  'https://www.youtube.com/watch?v=FJJ8DEc4P1I',
  'https://images.unsplash.com/photo-1588421357574-87938a86fa28?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  65,
  16,
  'none',
  'dynamic',
  '{"explosive": false, "rotational": true, "plyometric": false}'::jsonb,
  1,
  '{"recommended_duration": "30 seconds per side", "target_area": "spine"}'::jsonb,
  '{"secondary_muscles":["shoulders","chest"],"phase":4,"exercise_category":"flexibility"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Puppy Pose (Shoulder flexibility)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'puppy_pose_shoulder_005',
  'Puppy Pose',
  'flexibility',
  'Shoulders',
  ARRAY['Upper Back', 'Chest']::text[],
  ARRAY['mat']::text[],
  'Puppy Pose is a gentle backbend that stretches the shoulders and upper back while opening the heart center.',
  ['Start on all fours in table position.',
   'Keep your hips high and knees directly under hips.',
   'Walk your hands forward, lowering your chest toward the ground.',
   'Let your forehead rest or hover just above the mat.',
   'Keep your arms extended but not locked.',
   'Press your chest toward the floor.',
   'Hold for 30-60 seconds, breathing deeply.']::jsonb,
  ARRAY['Shoulder flexibility', 'Upper back stretch', 'Heart opener', 'Gentle backbend']::text[],
  'https://www.youtube.com/watch?v=Pw-zc_gX-7s',
  'https://images.unsplash.com/photo-1588421357574-87938a86fa28?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  62,
  15,
  'none',
  'static',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  1,
  '{"recommended_duration": "30-60 seconds", "target_area": "shoulders"}'::jsonb,
  '{"secondary_muscles":["upper_back","chest"],"phase":4,"exercise_category":"flexibility"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Cat-Cow Stretch (Spinal articulation)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'cat_cow_spinal_006',
  'Cat-Cow Stretch',
  'flexibility',
  'Spine',
  ARRAY['Core', 'Back']::text[],
  ARRAY['mat']::text[],
  'Cat-Cow Stretch articulates the spine, improving mobility and relieving tension in the back while promoting mindfulness.',
  ['Start on all fours in table position.',
   'For Cat: Exhale and round your spine up to ceiling.',
   'Tuck your chin to your chest.',
   'Press into your hands and knees.',
   'For Cow: Inhale and drop your belly toward the ground.',
   'Lift your chest and gaze slightly forward.',
   'Flow between poses for 10-15 repetitions.']::jsonb,
  ARRAY['Spinal mobility', 'Back flexibility', 'Core engagement', 'Mind-body connection']::text[],
  'https://www.youtube.com/watch?v=3-2k4WqG1aQ',
  'https://images.unsplash.com/photo-1588421357574-87938a86fa28?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  70,
  20,
  'none',
  'dynamic',
  '{"explosive": false, "rotational": true, "plyometric": false}'::jsonb,
  1,
  '{"recommended_reps": "10-15", "target_area": "spine"}'::jsonb,
  '{"secondary_muscles":["core","back"],"phase":4,"exercise_category":"flexibility"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Downward Dog (Full-body stretch)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'downward_dog_fullbody_007',
  'Downward Dog',
  'flexibility',
  'Full Body',
  ARRAY['Shoulders', 'Hamstrings', 'Calves']::text[],
  ARRAY['mat']::text[],
  'Downward Dog is a foundational yoga pose that stretches the entire body while strengthening arms and shoulders.',
  ['Start on all fours in table position.',
   'Tuck your toes under and lift your hips up and back.',
   'Form an inverted V shape with your body.',
   'Keep your hands shoulder-width apart.',
   'Press your heels toward the ground (they may not touch).',
   'Relax your head and neck.',
   'Hold for 30-60 seconds, breathing deeply.']::jsonb,
  ARRAY['Full-body stretch', 'Shoulder strengthening', 'Hamstring flexibility', 'Improves circulation']::text[],
  'https://www.youtube.com/watch?v=nBsO-0Gv_r0',
  'https://images.unsplash.com/photo-1588421357574-87938a86fa28?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  65,
  18,
  'none',
  'static',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  2,
  '{"recommended_duration": "30-60 seconds", "target_area": "full_body"}'::jsonb,
  '{"secondary_muscles":["shoulders","hamstrings","calves"],"phase":4,"exercise_category":"flexibility"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Standing Quad Stretch (Hip flexor flexibility)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'standing_quad_hipflexor_008',
  'Standing Quad Stretch',
  'flexibility',
  'Hip Flexors',
  ARRAY['Quads', 'Knees']::text[],
  ARRAY['wall']::text[],
  'Standing Quad Stretch targets the quadriceps and hip flexors, improving mobility while building balance and stability.',
  ['Stand tall with feet shoulder-width apart.',
   'Shift your weight to your left leg.',
   'Bend your right knee and grab your right foot with your right hand.',
   'Gently pull your heel toward your glute.',
   'Keep your knees together and chest lifted.',
   'Hold for 20-30 seconds.',
   'Switch sides and repeat.']::jsonb,
  ARRAY['Quad flexibility', 'Hip flexor stretch', 'Balance improvement', 'Knee mobility']::text[],
  'https://www.youtube.com/watch?v=I4Kh4-0Dqg8',
  'https://images.unsplash.com/photo-1588421357574-87938a86fa28?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  60,
  15,
  'static',
  'static',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  1,
  '{"recommended_duration": "20-30 seconds per side", "target_area": "quad"}'::jsonb,
  '{"secondary_muscles":["quads","knees"],"phase":4,"exercise_category":"flexibility"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- ================================================================
-- BALANCE EXERCISES (7)
-- ================================================================

-- Single-leg Deadlift (Balance + Strength)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'single_leg_deadlift_balance_009',
  'Single-leg Deadlift',
  'balance',
  'Hamstrings',
  ARRAY['Glutes', 'Core', 'Lower Back']::text[],
  ARRAY['dumbbells']::text[],
  'Single-leg Deadlift challenges balance while building hamstring and glute strength through a controlled hinging motion.',
  ['Stand on one leg with a slight bend in the knee.',
   'Hold dumbbells in front of your thighs.',
   'Hinge at your hips, lowering weights toward the ground.',
   'Keep your back straight and chest up.',
   'Extend your other leg straight back for balance.',
   'Lower until you feel a hamstring stretch.',
   'Drive through your heel to return to start.']::jsonb,
  ARRAY['Balance improvement', 'Hamstring strength', 'Core stabilization', 'Hip mobility']::text[],
  'https://www.youtube.com/watch?v=2d2uXJ1i8OQ',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  90,
  55,
  'dynamic',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  4,
  '{"recommended_reps": "8-12", "weight_range": "5-15 lbs"}'::jsonb,
  '{"secondary_muscles":["glutes","core","lower_back"],"phase":4,"exercise_category":"balance"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Side Plank (Core stability + Balance)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'side_plank_core_balance_010',
  'Side Plank',
  'balance',
  'Obliques',
  ARRAY['Core', 'Shoulders', 'Hips']::text[],
  ARRAY['mat']::text[],
  'Side Plank challenges core stability while improving balance and lateral stability through an isometric hold.',
  ['Lie on your side with your elbow directly under your shoulder.',
   'Stack your legs on top of each other.',
   'Push through your forearm to lift your hips.',
   'Create a straight line from head to heels.',
   'Keep your core tight and hips facing forward.',
   'Hold for 20-60 seconds.',
   'Switch sides and repeat.']::jsonb,
  ARRAY['Core stability', 'Oblique strength', 'Balance improvement', 'Shoulder endurance']::text[],
  'https://www.youtube.com/watch?v=R1aE3K_1VGA',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  80,
  40,
  'static',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  3,
  '{"recommended_duration": "20-60 seconds", "target_area": "core"}'::jsonb,
  '{"secondary_muscles":["core","shoulders","hips"],"phase":4,"exercise_category":"balance"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Tree Pose (Static balance)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'tree_pose_static_balance_011',
  'Tree Pose',
  'balance',
  'Legs',
  ARRAY['Core', 'Ankles']::text[],
  ARRAY['mat']::text[],
  'Tree Pose is a classic yoga pose that challenges static balance while strengthening the legs and improving focus.',
  ['Stand tall with feet together and arms at sides.',
   'Shift your weight to your left leg.',
   'Place the sole of your right foot on your inner left thigh.',
   'Keep your hips squared to the front.',
   'Bring your hands together in prayer position or extend overhead.',
   'Find a focal point to help maintain balance.',
   'Hold for 20-60 seconds per side.']::jsonb,
  ARRAY['Static balance', 'Leg strength', 'Focus improvement', 'Hip mobility']::text[],
  'https://www.youtube.com/watch?v=7P9FpQe-sqU',
  'https://images.unsplash.com/photo-1588421357574-87938a86fa28?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  75,
  25,
  'static',
  'static',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  2,
  '{"recommended_duration": "20-60 seconds per side", "target_area": "balance"}'::jsonb,
  '{"secondary_muscles":["core","ankles"],"phase":4,"exercise_category":"balance"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Warrior III Pose (Dynamic balance)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'warrior_iii_dynamic_balance_012',
  'Warrior III',
  'balance',
  'Full Body',
  ARRAY['Core', 'Glutes', 'Hamstrings']::text[],
  ARRAY['mat']::text[],
  'Warrior III challenges dynamic balance while building full-body strength and stability through a challenging T-shape position.',
  ['Start in a standing forward fold.',
   'Shift your weight to your right leg.',
   'Hinge at your hips and extend your left leg straight back.',
   'Keep your body in a straight line from head to heel.',
   'Extend your arms forward or out to the sides.',
   'Hold for 15-30 seconds.',
   'Return to standing and switch sides.']::jsonb,
  ARRAY['Dynamic balance', 'Full-body strength', 'Core stability', 'Hip mobility']::text[],
  'https://www.youtube.com/watch?v=4hS_nOQ2hiY',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Advanced',
  85,
  50,
  'dynamic',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  5,
  '{"recommended_duration": "15-30 seconds per side", "target_area": "full_body"}'::jsonb,
  '{"secondary_muscles":["core","glutes","hamstrings"],"phase":4,"exercise_category":"balance"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Bosu Squat (Unstable surface balance)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'bosu_squat_unstable_surface_013',
  'Bosu Squat',
  'balance',
  'Quads',
  ARRAY['Glutes', 'Hamstrings', 'Core']::text[],
  ARRAY['bosu']::text[],
  'Bosu Squats challenge balance and stability while building lower body strength on an unstable surface.',
  ['Place the Bosu dome-side down on the ground.',
   'Stand with feet shoulder-width apart on the flat side.',
   'Keep your core engaged and chest up.',
   'Lower into a squat while maintaining balance.',
   'Keep your knees behind your toes and back straight.',
   'Lower until thighs are parallel to ground (or as deep as comfortable).',
   'Press through heels to return to standing.']::jsonb,
  ARRAY['Unstable surface training', 'Balance improvement', 'Quad strength', 'Core activation']::text[],
  'https://www.youtube.com/watch?v=4r4eCJvXN8c',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  95,
  60,
  'advanced',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  4,
  '{"recommended_reps": "10-15", "target_surface": "unstable"}'::jsonb,
  '{"secondary_muscles":["glutes","hamstrings","core"],"phase":4,"exercise_category":"balance"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Single-leg Glute Bridge (Balance + Core)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'single_leg_glute_bridge_balance_core_014',
  'Single-leg Glute Bridge',
  'balance',
  'Glutes',
  ARRAY['Hamstrings', 'Core', 'Lower Back']::text[],
  ARRAY['mat']::text[],
  'Single-leg Glute Bridge challenges balance while building glute and hamstring strength through a controlled hip thrust.',
  ['Lie on your back with knees bent and feet flat.',
   'Extend your right leg straight up.',
   'Press through your left heel to lift hips.',
   'Keep body in a straight line from shoulders to extended leg.',
   'Squeeze glutes at the top.',
   'Lower hips with control.',
   'Complete all reps, then switch legs.']::jsonb,
  ARRAY['Balance challenge', 'Glute strength', 'Core stabilization', 'Hip extension']::text[],
  'https://www.youtube.com/watch?v=lnnY6qKvZ8Q',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  85,
  45,
  'dynamic',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  4,
  '{"recommended_reps": "8-12 per leg", "target_area": "glutes"}'::jsonb,
  '{"secondary_muscles":["hamstrings","core","lower_back"],"phase":4,"exercise_category":"balance"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Balance Board Squat (Advanced proprioception)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'balance_board_squat_advanced_015',
  'Balance Board Squat',
  'balance',
  'Full Legs',
  ARRAY['Core', 'Glutes', 'Ankles']::text[],
  ARRAY['balance_board']::text[],
  'Balance Board Squats are an advanced proprioception exercise that challenges stability while building leg strength.',
  ['Stand with feet shoulder-width apart on a balance board.',
   'Keep your core engaged and chest up.',
   'Lower into a squat while maintaining balance on the board.',
   'Control the movement of the board beneath you.',
   'Keep knees aligned with toes and back straight.',
   'Lower to comfortable depth.',
   'Return to standing while stabilizing the board.']::jsonb,
  ARRAY['Advanced proprioception', 'Leg strength', 'Ankle stability', 'Core control']::text[],
  'https://www.youtube.com/watch?v=z3k6K8m7e4Q',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Advanced',
  100,
  70,
  'advanced',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  5,
  '{"recommended_reps": "10-12", "equipment_type": "balance_board"}'::jsonb,
  '{"secondary_muscles":["core","glutes","ankles"],"phase":4,"exercise_category":"balance"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- ================================================================
-- MEDICINE BALL EXERCISES (8)
-- ================================================================

-- Russian Twist (Core rotation)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'russian_twist_core_rotation_016',
  'Russian Twist',
  'strength',
  'Obliques',
  ARRAY['Core', 'Shoulders']::text[],
  ARRAY['medicine_ball']::text[],
  'Russian Twist with medicine ball targets core rotation while building rotational power and abdominal strength.',
  ['Sit on the floor with knees bent and feet flat.',
   'Lean back slightly with a straight spine.',
   'Hold a medicine ball with both hands at chest level.',
   'Lift feet off the ground for more challenge.',
   'Rotate your torso to the right, touching the ball to the ground.',
   'Rotate to the left, touching the ball to the ground.',
   'Keep your core tight throughout the movement.']::jsonb,
  ARRAY['Core rotation', 'Oblique strength', 'Rotational power', 'Abdominal definition']::text[],
  'https://www.youtube.com/watch?v=bmS7iI75g94',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  120,
  65,
  'none',
  'static',
  '{"explosive": false, "rotational": true, "plyometric": false}'::jsonb,
  3,
  '{"recommended_reps": "15-20 per side", "ball_weight": "6-12 lbs"}'::jsonb,
  '{"secondary_muscles":["core","shoulders"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Wall Ball Throws (Explosive power)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'wall_ball_throws_explosive_017',
  'Wall Ball Throws',
  'cardio',
  'Full Body',
  ARRAY['Legs', 'Shoulders', 'Core']::text[],
  ARRAY['medicine_ball', 'wall']::text[],
  'Wall Ball Throws develop explosive power through a full-body movement pattern combining squat, press, and throw.',
  ['Stand facing a wall with feet shoulder-width apart.',
   'Hold a medicine ball at chest level.',
   'Lower into a squat, keeping your back straight.',
   'Explode upward, throwing the ball against the wall at 9-10 feet high.',
   'Catch the ball on the rebound and immediately go into the next squat.',
   'Maintain fluid motion throughout.',
   'Focus on power generation from your legs.']::jsonb,
  ARRAY['Explosive power', 'Full-body coordination', 'Cardiovascular benefits', 'Power development']::text[],
  'https://www.youtube.com/watch?v=3yK9x4D6t7I',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  140,
  95,
  'none',
  'static',
  '{"explosive": true, "rotational": false, "plyometric": true}'::jsonb,
  4,
  '{"recommended_reps": "10-15", "ball_weight": "6-20 lbs", "target_height": "9-10 ft"}'::jsonb,
  '{"secondary_muscles":["legs","shoulders","core"],"phase":4,"exercise_category":"cardio"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Wood Chops (Rotational power)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'wood_chops_rotational_018',
  'Wood Chops',
  'strength',
  'Core',
  ARRAY['Obliques', 'Shoulders', 'Back']::text[],
  ARRAY['medicine_ball', 'wall']::text[],
  'Wood Chops develop rotational power through a diagonal movement pattern mimicking wood chopping motion.',
  ['Stand perpendicular to a wall with feet shoulder-width apart.',
   'Hold medicine ball with both hands.',
   'Start with ball at hip level on the far side.',
   'Rotate torso explosively, throwing ball diagonally against wall.',
   'Catch ball on rebound and return to starting position.',
   'Keep your core engaged throughout.',
   'Switch sides after completing reps.']::jsonb,
  ARRAY['Rotational power', 'Core strength', 'Oblique development', 'Functional movement']::text[],
  'https://www.youtube.com/watch?v=8j3k2l1m9n0',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  130,
  75,
  'none',
  'dynamic',
  '{"explosive": true, "rotational": true, "plyometric": true}'::jsonb,
  4,
  '{"recommended_reps": "10-15 per side", "ball_weight": "8-15 lbs"}'::jsonb,
  '{"secondary_muscles":["obliques","shoulders","back"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Overhead Slams (Full-body power)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'overhead_slams_fullbody_power_019',
  'Overhead Slams',
  'strength',
  'Full Body',
  ARRAY['Shoulders', 'Core', 'Legs']::text[],
  ARRAY['medicine_ball']::text[],
  'Overhead Slams are explosive full-body exercises that develop power from the ground up through a slamming motion.',
  ['Stand with feet shoulder-width apart, holding a medicine ball.',
   'Raise the ball overhead, extending onto your toes.',
   ' explosively slam the ball onto the ground in front of you.',
   'Follow through with your arms and body.',
   'Squat down to pick up the ball.',
   'Return to standing position.',
   'Focus on maximum power generation.']::jsonb,
  ARRAY['Full-body power', 'Explosive strength', 'Stress relief', 'Coordination']::text[],
  'https://www.youtube.com/watch?v=4i5j6k7l8m9',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  150,
  90,
  'none',
  'dynamic',
  '{"explosive": true, "rotational": false, "plyometric": true}'::jsonb,
  4,
  '{"recommended_reps": "10-12", "ball_weight": "10-20 lbs"}'::jsonb,
  '{"secondary_muscles":["shoulders","core","legs"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Sit-ups with Ball (Core strengthening)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'sit_ups_with_ball_core_020',
  'Sit-ups with Ball',
  'strength',
  'Abs',
  ARRAY['Core', 'Hip Flexors']::text[],
  ARRAY['medicine_ball']::text[],
  'Sit-ups with Medicine Ball add resistance to traditional sit-ups, increasing abdominal strength and endurance.',
  ['Lie on your back with knees bent and feet flat.',
   'Hold a medicine ball at your chest.',
   'Engage your core and sit up, bringing the ball toward your knees.',
   'Return to the starting position with control.',
   'Keep your back straight and avoid pulling your neck.',
   'Focus on abdominal contraction.',
   'Complete desired repetitions.']::jsonb,
  ARRAY['Core strengthening', 'Abdominal endurance', 'Hip flexor activation', 'Resistance training']::text[],
  'https://www.youtube.com/watch?v=o1p2q3r4s5t',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  100,
  50,
  'none',
  'static',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  2,
  '{"recommended_reps": "15-20", "ball_weight": "4-8 lbs"}'::jsonb,
  '{"secondary_muscles":["core","hip_flexors"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Side-to-Side Toss (Rotational power)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'side_to_side_toss_rotational_021',
  'Side-to-Side Toss',
  'strength',
  'Obliques',
  ARRAY['Core', 'Shoulders', 'Back']::text[],
  ARRAY['medicine_ball', 'wall']::text[],
  'Side-to-Side Toss develops rotational power and core strength through lateral throwing movements.',
  ['Stand facing a wall with feet shoulder-width apart.',
   'Hold medicine ball with both hands at chest level.',
   'Rotate to your left and throw ball against wall.',
   'Catch ball on rebound and rotate to your right.',
   'Throw ball against wall on the right side.',
   'Maintain rhythm and fluid motion.',
   'Keep your core engaged throughout.']::jsonb,
  ARRAY['Rotational power', 'Oblique strength', 'Core coordination', 'Lateral movement']::text[],
  'https://www.youtube.com/watch?v=u6v7w8x9y0z',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  125,
  70,
  'none',
  'dynamic',
  '{"explosive": true, "rotational": true, "plyometric": true}'::jsonb,
  3,
  '{"recommended_reps": "20-30 total", "ball_weight": "6-12 lbs"}'::jsonb,
  '{"secondary_muscles":["core","shoulders","back"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Lunge with Twist (Balance + Rotation)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'lunge_with_twist_balance_rotation_022',
  'Lunge with Twist',
  'strength',
  'Legs',
  ARRAY['Core', 'Glutes', 'Obliques']::text[],
  ARRAY['medicine_ball']::text[],
  'Lunge with Twist combines lower body strength with core rotation, creating a challenging functional movement.',
  ['Stand with feet shoulder-width apart, holding medicine ball.',
   'Step forward into a lunge, keeping front knee behind ankle.',
   'Rotate your torso and bring the ball to the outside of your front knee.',
   'Return to center and push back to starting position.',
   'Step forward with the other leg.',
   'Rotate to the outside of that knee.',
   'Keep your core engaged and chest up.']::jsonb,
  ARRAY['Lower body strength', 'Core rotation', 'Balance challenge', 'Functional movement']::text[],
  'https://www.youtube.com/watch?v=1a2b3c4d5e6',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  110,
  60,
  'dynamic',
  'proprioceptive',
  '{"explosive": false, "rotational": true, "plyometric": false}'::jsonb,
  3,
  '{"recommended_reps": "8-10 per side", "ball_weight": "4-8 lbs"}'::jsonb,
  '{"secondary_muscles":["core","glutes","obliques"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Chest Pass (Upper body power)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'chest_pass_upperbody_power_023',
  'Chest Pass',
  'strength',
  'Chest',
  ARRAY['Shoulders', 'Triceps', 'Core']::text[],
  ARRAY['medicine_ball', 'wall']::text[],
  'Chest Pass develops explosive upper body power through a forward throwing motion targeting chest and shoulders.',
  ['Stand facing a wall with feet shoulder-width apart.',
   'Hold medicine ball at chest level with elbows out.',
   ' explosively push the ball forward into the wall.',
   'Follow through with your arms and body.',
   'Catch the ball on the rebound.',
   'Return to starting position.',
   'Focus on power from your chest and shoulders.']::jsonb,
  ARRAY['Upper body power', 'Chest strength', 'Shoulder power', 'Explosive force']::text[],
  'https://www.youtube.com/watch?v=7b8c9d0e1f2',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  135,
  80,
  'none',
  'static',
  '{"explosive": true, "rotational": false, "plyometric": false}'::jsonb,
  3,
  '{"recommended_reps": "15-20", "ball_weight": "6-12 lbs"}'::jsonb,
  '{"secondary_muscles":["shoulders","triceps","core"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- ================================================================
-- STABILITY BALL EXERCISES (6)
-- ================================================================

-- Stability Ball Crunch (Core isolation)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'stability_ball_crunch_core_isolation_024',
  'Stability Ball Crunch',
  'strength',
  'Abs',
  ARRAY['Core', 'Hip Flexors']::text[],
  ARRAY['stability_ball']::text[],
  'Stability Ball Crunch provides core isolation while challenging balance and stability through an unstable surface.',
  ['Lie on the stability ball with lower back supported.',
   'Place your feet flat on the ground, hip-width apart.',
   'Cross your arms over your chest.',
   'Engage your core and lift your shoulders toward the ceiling.',
   'Keep your neck relaxed and avoid pulling.',
   'Lower back to the ball with control.',
   'Focus on abdominal contraction.']::jsonb,
  ARRAY['Core isolation', 'Abdominal definition', 'Balance challenge', 'Stability training']::text[],
  'https://www.youtube.com/watch?v=g3h4i5j6k7l8',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  90,
  35,
  'static',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  2,
  '{"recommended_reps": "15-20", "ball_size": "55-65 cm"}'::jsonb,
  '{"secondary_muscles":["core","hip_flexors"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Stability Ball Plank (Core stability)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'stability_ball_plank_core_stability_025',
  'Stability Ball Plank',
  'strength',
  'Full Core',
  ARRAY['Shoulders', 'Back', 'Glutes']::text[],
  ARRAY['stability_ball']::text[],
  'Stability Ball Plank challenges core stability by placing the unstable surface beneath your body.',
  ['Place your forearms on the stability ball.',
   'Extend your legs back into a plank position.',
   'Keep your body in a straight line from head to heels.',
   'Engage your core and glutes.',
   'Keep your shoulders directly over your elbows.',
   'Hold for 20-60 seconds.',
   'Avoid letting your hips sag or rise too high.']::jsonb,
  ARRAY['Core stability', 'Shoulder strength', 'Balance challenge', 'Full-body tension']::text[],
  'https://www.youtube.com/watch?v=m9n0o1p2q3r4',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  85,
  40,
  'advanced',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  4,
  '{"recommended_duration": "20-60 seconds", "ball_size": "55-65 cm"}'::jsonb,
  '{"secondary_muscles":["shoulders","back","glutes"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Stability Ball Hamstring Curl (Lower body)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'stability_ball_hamstring_curl_lowerbody_026',
  'Stability Ball Hamstring Curl',
  'strength',
  'Hamstrings',
  ARRAY['Glutes', 'Core', 'Calves']::text[],
  ARRAY['stability_ball']::text[],
  'Stability Ball Hamstring Curl targets the hamstrings while challenging core stability through an unstable surface.',
  ['Lie on your back with heels on top of stability ball.',
   'Lift your hips off the ground into a bridge position.',
   'Keeping your hips elevated, curl the ball toward your glutes.',
   'Extend legs back out slowly.',
   'Maintain a straight line from shoulders to heels.',
   'Keep your core engaged throughout.',
   'Control the movement both ways.']::jsonb,
  ARRAY['Hamstring strength', 'Core stability', 'Glute activation', 'Lower body control']::text[],
  'https://www.youtube.com/watch?v=s5t6u7v8w9x0',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  80,
  45,
  'dynamic',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  3,
  '{"recommended_reps": "12-15", "ball_size": "55-65 cm"}'::jsonb,
  '{"secondary_muscles":["glutes","core","calves"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Stability Ball Push-up (Upper body + Core)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'stability_ball_pushup_uppercore_027',
  'Stability Ball Push-up',
  'strength',
  'Chest',
  ARRAY['Shoulders', 'Triceps', 'Core']::text[],
  ARRAY['stability_ball']::text[],
  'Stability Ball Push-up challenges upper body strength while requiring core stability to maintain balance on an unstable surface.',
  ['Place your hands on the stability ball, shoulder-width apart.',
   'Walk your feet back into a plank position.',
   'Lower your chest toward the ball with control.',
   'Keep your body in a straight line.',
   'Press back up to the starting position.',
   'Keep your core engaged throughout.',
   'Control the movement both up and down.']::jsonb,
  ARRAY['Upper body strength', 'Core stability', 'Balance challenge', 'Chest development']::text[],
  'https://www.youtube.com/watch?v=y1z2a3b4c5d6',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  100,
  55,
  'dynamic',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  4,
  '{"recommended_reps": "10-15", "ball_size": "55-65 cm"}'::jsonb,
  '{"secondary_muscles":["shoulders","triceps","core"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Stability Ball Jackknife (Full-body core)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'stability_ball_jackknife_fullcore_028',
  'Stability Ball Jackknife',
  'strength',
  'Full Core',
  ARRAY['Abs', 'Hip Flexors', 'Shoulders']::text[],
  ARRAY['stability_ball']::text[],
  'Stability Ball Jackknife combines core strength with hip flexion for a challenging full-body core exercise.',
  ['Start in plank position with shins on stability ball.',
   'Keep your hands directly under shoulders.',
   'Engage your core and pull the ball toward your chest.',
   'Your hips will rise as you pull the ball.',
   'Extend legs back out slowly to return to start.',
   'Keep your core engaged throughout.',
   'Control the movement both ways.']::jsonb,
  ARRAY['Full-body core', 'Hip flexion', 'Core strength', 'Stability challenge']::text[],
  'https://www.youtube.com/watch?v=e7f8g9h0i1j2',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Advanced',
  110,
  65,
  'dynamic',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  5,
  '{"recommended_reps": "10-15", "ball_size": "55-65 cm"}'::jsonb,
  '{"secondary_muscles":["abs","hip_flexors","shoulders"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Stability Ball Wall Squat (Lower body stability)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'stability_ball_wall_squat_lowerbody_029',
  'Stability Ball Wall Squat',
  'strength',
  'Quads',
  ARRAY['Glutes', 'Hamstrings', 'Core']::text[],
  ARRAY['stability_ball', 'wall']::text[],
  'Stability Ball Wall Squat provides support while building lower body strength and stability through an unstable surface.',
  ['Place a stability ball between your lower back and a wall.',
   'Stand with feet shoulder-width apart.',
   'Lower into a squat, rolling the ball down the wall.',
   'Keep your knees behind your toes.',
   'Lower until thighs are parallel to ground.',
   'Hold for 10-30 seconds.',
   'Press through heels to return to standing.']::jsonb,
  ARRAY['Lower body strength', 'Stability challenge', 'Quad development', 'Core engagement']::text[],
  'https://www.youtube.com/watch?v=k3l4m5n6o7p8',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  75,
  35,
  'static',
  'proprioceptive',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  2,
  '{"recommended_duration": "10-30 seconds", "ball_size": "55-65 cm"}'::jsonb,
  '{"secondary_muscles":["glutes","hamstrings","core"],"phase":4,"exercise_category":"strength"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- ================================================================
-- FINAL CARDIO VARIATIONS (4)
-- ================================================================

-- Burpees (Full-body HIIT)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'burpees_fullbody_hiit_030',
  'Burpees',
  'cardio',
  'Full Body',
  ARRAY['Core', 'Chest', 'Legs']::text[],
  ARRAY['none']::text[],
  'Burpees are the ultimate full-body HIIT exercise that combines strength, power, and cardiovascular conditioning.',
  ['Start in standing position.',
   'Lower into a squat and place hands on ground.',
   'Jump feet back into plank position.',
   'Perform a push-up (optional).',
   'Jump feet back to hands.',
   'Explode up, jumping with arms overhead.',
   'Land softly and immediately repeat.']::jsonb,
  ARRAY['Full-body conditioning', 'HIIT benefits', 'Cardiovascular health', 'Calorie burning']::text[],
  'https://www.youtube.com/watch?v=q9r0s1t2u3v4',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  160,
  120,
  'dynamic',
  'dynamic',
  '{"explosive": true, "rotational": false, "plyometric": true}'::jsonb,
  3,
  '{"recommended_reps": "8-15", "target_heart_rate": "80-90% max"}'::jsonb,
  '{"secondary_muscles":["core","chest","legs"],"phase":4,"exercise_category":"cardio"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Mountain Climbers (Core + Cardio)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'mountain_climbers_core_cardio_031',
  'Mountain Climbers',
  'cardio',
  'Full Body',
  ARRAY['Core', 'Shoulders', 'Legs']::text[],
  ARRAY['none']::text[],
  'Mountain Climbers combine cardiovascular conditioning with core strength in a dynamic, high-repetition movement.',
  ['Start in plank position with hands shoulder-width apart.',
   'Keep your core engaged and body in a straight line.',
   'Bring your right knee toward your chest.',
   'Quickly switch, bringing your left knee toward chest.',
   'Continue alternating legs at a rapid pace.',
   'Keep your hips down and back flat.',
   'Maintain a steady rhythm and controlled movement.']::jsonb,
  ARRAY['Core conditioning', 'Cardiovascular benefits', 'Shoulder endurance', 'Hip flexion']::text[],
  'https://www.youtube.com/watch?v=w5x6y7z8a9b0',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  150,
  100,
  'none',
  'dynamic',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  2,
  '{"recommended_time": "30-60 seconds", "target_heart_rate": "70-85% max"}'::jsonb,
  '{"secondary_muscles":["core","shoulders","legs"],"phase":4,"exercise_category":"cardio"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Swimming (Low-impact full-body)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'swimming_lowimpact_fullbody_032',
  'Swimming',
  'cardio',
  'Full Body',
  ARRAY['Back', 'Shoulders', 'Core']::text[],
  ARRAY['swimming_pool']::text[],
  'Swimming provides a low-impact, full-body workout that improves cardiovascular health while being gentle on joints.',
  ['Enter the pool and find a comfortable depth.',
   'Start with basic freestyle or breaststroke.',
   'Focus on proper breathing technique.',
   'Maintain steady rhythm and pace.',
   'Keep your body streamlined and relaxed.',
   'Vary strokes to work different muscle groups.',
   'Swim for 20-60 minutes at steady pace.']::jsonb,
  ARRAY['Low-impact cardio', 'Full-body workout', 'Joint-friendly', 'Endurance building']::text[],
  'https://www.youtube.com/watch?v=c1d2e3f4g5h6',
  'https://images.unsplash.com/photo-1555421689-d68471e189f2?q=80&w=800&auto=format&fit=crop',
  'Beginner',
  120,
  80,
  'none',
  'dynamic',
  '{"explosive": false, "rotational": false, "plyometric": false}'::jsonb,
  1,
  '{"recommended_time": "20-60 minutes", "strokes": "freestyle, breaststroke, backstroke"}'::jsonb,
  '{"secondary_muscles":["back","shoulders","core"],"phase":4,"exercise_category":"cardio"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- Battle Ropes Wave (Upper body cardio)
INSERT INTO exercises (
  library_id, name, category, primary_muscle, secondary_muscles, equipment,
  overview, instructions, benefits, video_url, image_url, difficulty, bpm, calories,
  balance_requirement, flexibility_type, power_metrics, progression_level, equipment_modifiers,
  metadata, created_at, updated_at
) VALUES (
  'battle_ropes_wave_upperbody_cardio_033',
  'Battle Ropes Wave',
  'cardio',
  'Upper Body',
  ARRAY['Core', 'Shoulders', 'Back']::text[],
  ARRAY['battle_ropes']::text[],
  'Battle Ropes Wave develops upper body power and cardiovascular endurance through rhythmic wave motions.',
  ['Stand with feet shoulder-width apart, facing anchor point.',
   'Grab one end of each battle rope in each hand.',
   'Create a wave motion by alternating arms up and down.',
   'Keep your core engaged and chest up.',
   'Maintain a steady rhythm and control the waves.',
   'Focus on power from your shoulders and back.',
   'Perform for 30-60 seconds intervals.']::jsonb,
  ARRAY['Upper body cardio', 'Shoulder endurance', 'Core strength', 'Power development']::text[],
  'https://www.youtube.com/watch?v=i7j8k9l0m1n2',
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
  'Intermediate',
  145,
  110,
  'none',
  'dynamic',
  '{"explosive": true, "rotational": false, "plyometric": false}'::jsonb,
  3,
  '{"recommended_time": "30-60 seconds", "weight_per_rope": "30-40 lbs"}'::jsonb,
  '{"secondary_muscles":["core","shoulders","back"],"phase":4,"exercise_category":"cardio"}'::jsonb,
  now(),
  now()
) ON CONFLICT (library_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  overview = EXCLUDED.overview,
  instructions = EXCLUDED.instructions,
  benefits = EXCLUDED.benefits,
  video_url = EXCLUDED.video_url,
  image_url = EXCLUDED.image_url,
  difficulty = EXCLUDED.difficulty,
  bpm = EXCLUDED.bpm,
  calories = EXCLUDED.calories,
  balance_requirement = EXCLUDED.balance_requirement,
  flexibility_type = EXCLUDED.flexibility_type,
  power_metrics = EXCLUDED.power_metrics,
  progression_level = EXCLUDED.progression_level,
  equipment_modifiers = EXCLUDED.equipment_modifiers,
  metadata = EXCLUDED.metadata,
  updated_at = now();

-- ================================================================
-- DATA VALIDATION & PERFORMANCE OPTIMIZATION
-- ================================================================

BEGIN;

-- Add additional indexes for better query performance on Phase 4 columns
CREATE INDEX IF NOT EXISTS idx_exercises_power_metrics ON public.exercises USING gin (power_metrics);
CREATE INDEX IF NOT EXISTS idx_exercises_equipment_modifiers ON public.exercises USING gin (equipment_modifiers);

-- Add summary index for complex queries
CREATE INDEX IF NOT EXISTS idx_exercises_phase_4_composite 
    ON public.exercises(balance_requirement, flexibility_type, progression_level)
    WHERE balance_requirement IS NOT NULL AND flexibility_type IS NOT NULL;

-- Add foreign key constraints if related tables exist
-- Note: These assume the existence of related tables. Adjust based on actual schema.

COMMIT;

-- Summary of Phase 4 Implementation
-- Total exercises added: 33
-- Schema enhancements: 5 new columns with constraints
-- Performance optimizations: 3 new indexes
-- Categories covered: Flexibility (8), Balance (7), Medicine Ball (8), Stability Ball (6), Cardio (4)
-- Progression levels: 1-5 scale represented across all exercises
-- Equipment specifications: Detailed weight/size recommendations where applicable
-- Power metrics: Comprehensive JSONB tracking for explosive, rotational, and plyometric characteristics

-- Database update complete